### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'message_id'

### ISSUE THREAD

**Issue by ghost** [sfan5/secretlounge-ng#28]
Hi, I have this problem, but idk why

```
2021-03-22 02:38:39,923 Exception raised during queued message
Traceback (most recent call last):
  File "/home/ogp_agent/OGP_User_Files/8/src/telegram.py", line 317, in call
    self.func()
  File "/home/ogp_agent/OGP_User_Files/8/src/telegram.py", line 475, in f
    ch.saveMapping(user_id, msid, ev2.message_id)
AttributeError: 'NoneType' object has no attribute 'message_id'
```
[telegram.txt](https://github.com/sfan5/secretlounge-ng/files/6179749/telegram.txt)
[script.log](https://github.com/sfan5/secretlounge-ng/files/6179755/script.log)

**Comment by sfan5** [comment]
`resend_message()` must always return the answer from the Telegram API.
So if you call `bot.send_message` you must return that.
